'use server'

import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { getSupabaseAdmin } from '@/lib/supabase/admin'
import type { WidgetConfig, WidgetConfigUpdate } from '@/types/database'

async function getAuthenticatedCompanyId(): Promise<string> {
  const supabase = await createClient()

  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser()

  if (authError || !user) {
    redirect('/login')
  }

  const { data: company, error: companyError } = await supabase
    .from('companies')
    .select('id')
    .eq('email', user.email!)
    .single()

  if (companyError || !company) {
    throw new Error('Company not found')
  }

  return company.id
}

export async function enableWidget(): Promise<WidgetConfig> {
  const companyId = await getAuthenticatedCompanyId()
  const supabaseAdmin = getSupabaseAdmin()

  // Check if config exists
  const { data: existingConfig } = await supabaseAdmin
    .from('widget_configs')
    .select('*')
    .eq('company_id', companyId)
    .single()

  if (existingConfig) {
    // Update to enabled
    const { data: updatedConfig, error } = await supabaseAdmin
      .from('widget_configs')
      .update({ enabled: true })
      .eq('id', existingConfig.id)
      .select()
      .single()

    if (error) {
      throw new Error('Failed to enable widget')
    }

    revalidatePath('/dashboard/widget')
    return updatedConfig
  } else {
    // Create new config (api_key will be auto-generated by trigger)
    const { data: newConfig, error } = await supabaseAdmin
      .from('widget_configs')
      .insert({
        company_id: companyId,
        enabled: true,
        api_key: '', // Will be set by trigger
      })
      .select()
      .single()

    if (error) {
      throw new Error('Failed to create widget config')
    }

    revalidatePath('/dashboard/widget')
    return newConfig
  }
}

export async function disableWidget(): Promise<WidgetConfig> {
  const companyId = await getAuthenticatedCompanyId()
  const supabaseAdmin = getSupabaseAdmin()

  const { data: updatedConfig, error } = await supabaseAdmin
    .from('widget_configs')
    .update({ enabled: false })
    .eq('company_id', companyId)
    .select()
    .single()

  if (error) {
    throw new Error('Failed to disable widget')
  }

  revalidatePath('/dashboard/widget')
  return updatedConfig
}

export async function updateWidgetConfig(
  updates: WidgetConfigUpdate
): Promise<WidgetConfig> {
  const companyId = await getAuthenticatedCompanyId()
  const supabaseAdmin = getSupabaseAdmin()

  const { data: updatedConfig, error } = await supabaseAdmin
    .from('widget_configs')
    .update(updates)
    .eq('company_id', companyId)
    .select()
    .single()

  if (error) {
    console.error('Update widget config error:', error)
    throw new Error('Failed to update widget config')
  }

  revalidatePath('/dashboard/widget')
  return updatedConfig
}
